[build]
  command = "npm ci && npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."app"]
  included_files = ["src/views/**", "public/**"]
  external_node_modules = ["ejs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
